version: "3.9"
services:
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
