'use client';

import { Language } from '@/enums/Language';
import { vi } from 'date-fns/locale';
import { access } from 'fs';
import type React from 'react';

import { createContext, useContext, useState, useEffect } from 'react';

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations = {
  en: {
    user: 'User',
    home: 'Home',
    search: 'Search',
    create: 'Create',
    notifications: 'Notifications',
    profile: 'Profile',
    settings: 'Settings',
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot Password',
    changePassword: 'Change Password',
    editProfile: 'Edit Profile',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    logout: 'Logout',
    post: 'Post',
    comment: 'Comment',
    like: 'Like',
    repost: 'Repost',
    share: 'Share',
    delete: 'Delete',
    edit: 'Edit',
    update: 'Update',
    save: 'Save',
    cancel: 'Cancel',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    bio: 'Bio',
    displayName: 'Display Name',
    website: 'Website',
    avatar: 'Avatar',
    translate: 'Translate',
    viewEditHistory: 'View Edit History',
    reportContent: 'Report Content',
    followUser: 'Follow',
    unfollowUser: 'Unfollow',
    google: 'Google',
    error: 'Error',
    banned: 'You are banned from this platform.',
    emailNotVerified:
      'Your email is not verified. \n We have sent a verification email to your registered email address. Please check your inbox and verify your email to access all features.',
    emailVerified: 'Your email is verified.',
    emptyFields: 'Please fill in all fields.',
    loading: 'Loading...',
    loginFailed: 'Login failed. Please check your credentials.',
    success: 'Success',
    googleLoginSuccess: 'Google login successful!',
    googleLoginFailed: 'Google login failed or banned.',
    verifySuccess: 'Email verification successful!',
    verifySuccessDescription:
      'Your email has been successfully verified. Your account is now active and you can start using all features.',
    ifNotRedirect:
      'You will be automatically redirected to the home page in a few seconds.',
    resendEmailSuccess: 'Verification email resent successfully!',
    resendEmailFailed: 'Failed to resend verification email.',
    name: 'Name',
    registerFailed: 'Account or email already exists or is invalid.',
    followers: 'Followers',
    following: 'Following',
    loading_image: 'Loading image...',
    avatarUpdated: 'Avatar updated successfully!',
    avatarUpdateFailed: 'Failed to update avatar.',
    wallpaperUpdated: 'Wallpaper updated successfully!',
    wallpaperUpdateFailed: 'Failed to update wallpaper.',
    uploading: 'Uploading...',
    uploadFailed: 'Upload failed.',
    nameAndUsernameRequired: 'Name and username are required fields.',
    profileUpdated: 'Profile has been updated.',
    saving: 'Saving...',
    settingUpdated: 'Setting has been updated.',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    passwordChanged: 'Password changed successfully!',
    passwordChangeFailed: 'Failed to change password.',
    passwordNotSuitable: 'Password does not meet the requirements.',
    passwordsDoNotMatch: 'Passwords do not match.',
    passwordRequirements:
      'Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character.',
    passwordMustMatch: 'Password must match the confirmation password.',
    threadDetails: 'Thread Details',
    public: 'Public',
    followers_only: 'Followers Only',
    only_me: 'Only Me',
    select_privacy: 'Select Privacy',
    post_empty: 'Post content cannot be empty.',
    post_created: 'Post created successfully!',
    post_create_failed: 'Failed to create post.',
    post_updated: 'Post updated successfully!',
    post_update_failed: 'Failed to update post.',
    post_deleted: 'Post deleted successfully!',
    post_delete_failed: 'Failed to delete post.',
    no_comment_yet: 'No comments yet.',
    comment_created: 'Comment created successfully!',
    comment_create_failed: 'Failed to create comment.',
    noPosts: 'No post yet.',
    noReposts: 'No reposts yet.',
    deletePost: 'Delete Post',
    confirmDeletePost: 'Are you sure you want to delete this post?',
    threadDetail: 'Thread Detail',
    updating: 'Updating...',
    posting: 'Posting...',
    noNotifications: 'No notifications yet.',
    notification_like: 'liked your post',
    notification_likes: 'and others liked your post',
    notification_comment: 'commented on your post',
    notification_repost: 'reposted your post',
    notification_reosts: 'and others reposted your post',
    notification_follow: 'followed you',
    notification: 'Notification',
    viewPost: 'View Post',
    markAllAsRead: 'Mark all as read',
    loadingMoreNotifications: 'Loading more notifications...',
    noMoreNotifications: 'No more notifications.',
    follow: 'Follow',
    unfollow: 'Unfollow',
    noFollowers: 'Have no followers',
    noFollowing: 'Have no following ',
    removeFollower: 'Remove Follower',
    search_user: 'Search for users...',
    search_post: 'Search for posts...',
    no_user_found_for: 'User not found for',
    no_post_found_for: 'Post not found for',
    try_search_different_keywords:
      'Try searching with different keywords or check your spelling.',
    searching_user: 'Searching for users...',
    searching_post: 'Searching for posts...',
    post_something: 'Post something...',
    feed: 'Feed',
    feed_loading: 'Loading feed...',
    feed_empty: 'Your feed is empty.',
    feed_empty_description: `Follow other users to see their posts in your feed. The more people
            you follow, the more content you'll see here.`,
    find_people_follow: 'Find people to follow',
    refetch_feed: 'Refetch Feed',
    create_first_post: 'Create your first post',
    adminPanel: 'Admin Panel',
    dashboard: 'Dashboard',
    users: 'Users',
    reportedPosts: 'Reported Posts',
    reportSuccess: 'Report submitted successfully!',
    reportFailed: 'Failed to submit report.',
    theme: 'Theme',
    themePreferences: 'Theme Preferences',
    selectTheme: 'Select Theme',
    lightTheme: 'Light Theme',
    darkTheme: 'Dark Theme',
    systemTheme: 'System Theme',
    languageSettings: 'Language Settings',
    selectLanguage: 'Select Language',
    vietnamese: 'Vietnamese',
    english: 'English',
    japanese: 'Japanese',
    preview: 'Preview',
    userManagement: 'User Management',
    manageUsersDescription: 'Manage users and modify users.',
    accessUserList: 'Access user list',
    manageUsers: 'Manage Users',
    reviewReportedContent: 'Review reported content',
    viewReportedPostsDescription:
      'Review and manage posts that have been reported by users.',
    manageReports: 'Manage Reports',
    preferences: 'Preferences',
    action: 'Action',
    ban: 'Ban',
    unban: 'Unban',
    role: 'Role',
    status: 'Status',
    admin: 'Admin',
    active: 'Active',
    statusFilter: 'Status Filter',
    allStatuses: 'All Statuses',
    pendingReview: 'Pending Review',
    approved: 'Approved',
    reportCount: 'Report Count',
    allReports: 'All Reports',
    lowReport: 'Low Report',
    mediumReport: 'Medium Report',
    highReport: 'High Report',
    author: 'Author',
    contentPreview: 'Content Preview',
    visibility: 'Visibility',
    date: 'Date',
    view: 'View',
    approve: 'Approve',
    reports: 'reports',
    hide: 'Hide',
    creating: 'Creating',
    create_done: 'Create Done',
    banPost: 'Ban Post',
    banPostConfirmation: 'Are you sure you want to ban this post?',
    approvePost: 'Approve Post',
    approvePostConfirmation: 'Are you sure you want to approve this post?',
    viewReportedPost: 'View Reported Post',
    close: 'Close',
    banUser: 'Ban User',
    unbanUser: 'Unban User',
    banUserConfirmation: 'Are you sure you want to ban this user?',
    unbanUserConfirmation: 'Are you sure you want to unban this user?',
    app: 'App',
  },
  vi: {
    user: 'Người dùng',
    home: 'Trang chủ',
    search: 'Tìm kiếm',
    create: 'Tạo mới',
    notifications: 'Thông báo',
    profile: 'Hồ sơ',
    settings: 'Cài đặt',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    forgotPassword: 'Quên mật khẩu',
    changePassword: 'Đổi mật khẩu',
    editProfile: 'Chỉnh sửa hồ sơ',
    darkMode: 'Chế độ tối',
    lightMode: 'Chế độ sáng',
    language: 'Ngôn ngữ',
    logout: 'Đăng xuất',
    post: 'Bài viết',
    comment: 'Bình luận',
    like: 'Thích',
    repost: 'Chia sẻ lại',
    share: 'Chia sẻ',
    delete: 'Xóa',
    edit: 'Chỉnh sửa',
    update: 'Cập nhật',
    save: 'Lưu',
    cancel: 'Hủy',
    username: 'Tên người dùng',
    email: 'Email',
    password: 'Mật khẩu',
    confirmPassword: 'Xác nhận mật khẩu',
    bio: 'Tiểu sử',
    displayName: 'Tên hiển thị',
    website: 'Trang web',
    avatar: 'Ảnh đại diện',
    translate: 'Dịch',
    viewEditHistory: 'Xem lịch sử chỉnh sửa',
    reportContent: 'Báo cáo nội dung',
    followUser: 'Theo dõi',
    unfollowUser: 'Bỏ theo dõi',
    google: 'Google',
    error: 'Lỗi',
    banned: 'Bạn đã bị cấm khỏi nền tảng này.',
    emailNotVerified:
      'Email của bạn chưa được xác minh. \n Chúng tôi đã gửi một email xác minh đến địa chỉ email đã đăng ký của bạn. Vui lòng kiểm tra hộp thư đến của bạn và xác minh email của bạn để truy cập tất cả các tính năng.',
    emailVerified: 'Email của bạn đã được xác minh.',
    emptyFields: 'Vui lòng điền vào tất cả các trường.',
    loading: 'Đang tải...',
    loginFailed:
      'Đăng nhập thất bại. Vui lòng kiểm tra thông tin đăng nhập của bạn.',
    success: 'Thành công',
    googleLoginSuccess: 'Đăng nhập Google thành công!',
    googleLoginFailed: 'Đăng nhập Google thất bại hoặc bị cấm.',
    verifySuccess: 'Xác minh email thành công!',
    verifySuccessDescription:
      'Email của bạn đã được xác minh thành công. Tài khoản của bạn hiện đã hoạt động và bạn có thể bắt đầu sử dụng tất cả các tính năng.',
    ifNotRedirect:
      'Bạn sẽ được tự động chuyển hướng đến trang chủ trong vài giây.',
    resendEmailSuccess: 'Gửi lại email xác minh thành công!',
    resendEmailFailed: 'Gửi lại email xác minh thất bại.',
    name: 'Tên',
    registerFailed: 'Tài khoản hoặc email đã tồn tại hoặc không hợp lệ.',
    followers: 'Người theo dõi',
    following: 'Người đang theo dõi',
    loading_image: 'Đang tải ảnh...',
    avatarUpdated: 'Cập nhật ảnh đại diện thành công!',
    avatarUpdateFailed: 'Cập nhật ảnh đại diện thất bại.',
    wallpaperUpdated: 'Cập nhật hình nền thành công!',
    wallpaperUpdateFailed: 'Cập nhật hình nền thất bại.',
    uploading: 'Đang tải lên...',
    uploadFailed: 'Tải lên thất bại.',
    nameAndUsernameRequired: 'Tên và tên người dùng là các trường bắt buộc.',
    profileUpdated: 'Thông tin cá nhân đã được cập nhật. ',
    saving: 'Đang lưu...',
    settingUpdated: 'Cài đặt đã được cập nhật.',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    passwordChanged: 'Đổi mật khẩu thành công!',
    passwordChangeFailed: 'Đổi mật khẩu thất bại.',
    passwordNotSuitable: 'Mật khẩu không đáp ứng yêu cầu.',
    passwordsDoNotMatch: 'Mật khẩu không khớp.',
    passwordRequirements:
      'Mật khẩu phải chứa ít nhất một chữ cái viết hoa, một chữ cái viết thường, một số và một ký tự đặc biệt.',
    passwordMustMatch: 'Mật khẩu phải khớp với mật khẩu xác nhận.',
    threadDetails: 'Chi tiết bài viết',
    public: 'Công khai',
    followers_only: 'Chỉ người theo dõi',
    only_me: 'Chỉ mình tôi',
    select_privacy: 'Chọn quyền riêng tư',
    post_empty: 'Nội dung bài viết không được để trống.',
    post_created: 'Bài viết đã được tạo thành công!',
    post_create_failed: 'Tạo bài viết thất bại.',
    post_updated: 'Bài viết đã được cập nhật thành công!',
    post_update_failed: 'Cập nhật bài viết thất bại.',
    post_deleted: 'Bài viết đã được xóa thành công!',
    post_delete_failed: 'Xóa bài viết thất bại.',
    no_comment_yet: 'Chưa có bình luận nào.',
    comment_created: 'Bình luận đã được tạo thành công!',
    comment_create_failed: 'Tạo bình luận thất bại.',
    noPosts: 'Chưa có bài viết nào.',
    noReposts: 'Chưa có bài đăng lại nào.',
    deletePost: 'Xóa bài viết',
    confirmDeletePost: 'Bạn có chắc chắn muốn xóa bài viết này không?',
    threadDetail: 'Chi tiết bài viết',
    updating: 'Cập nhật...',
    posting: 'Đăng...',
    noNotifications: 'Chưa có thông báo nào.',
    notification_like: 'đã thích bài viết của bạn',
    notification_likes: 'và những người khác đã thích bài viết của bạn',
    notification_comment: 'đã bình luận về bài viết của bạn',
    notification_repost: 'đã chia sẻ lại bài viết của bạn',
    notification_reosts: 'và những người khác đã chia sẻ lại bài viết của bạn',
    notification_follow: 'đã theo dõi bạn',
    notification: 'Thông báo',
    viewPost: 'Xem bài viết',
    markAllAsRead: 'Đánh dấu tất cả là đã đọc',
    loadingMoreNotifications: 'Đang tải thêm thông báo...',
    noMoreNotifications: 'Không còn thông báo nào nữa.',
    follow: 'Theo dõi',
    unfollow: 'Bỏ theo dõi',
    noFollowers: 'Không có người theo dõi',
    noFollowing: 'Không theo dõi người nào',
    removeFollower: 'Huỷ người theo dõi',
    search_user: 'Tìm kiếm người dùng...',
    search_post: 'Tìm kiếm bài viết...',
    no_user_found_for: 'Không tìm thấy người dùng cho',
    no_post_found_for: 'Không tìm thấy bài viết cho',
    try_search_different_keywords:
      'Thử tìm kiếm với các từ khóa khác hoặc kiểm tra chính tả của bạn.',
    searching_user: 'Đang tìm kiếm người dùng...',
    searching_post: 'Đang tìm kiếm bài viết...',
    post_something: 'Đăng một cái gì đó...',
    feed: 'Bảng tin',
    feed_loading: 'Đang tải bảng tin...',
    feed_empty: 'Bảng tin của bạn đang trống.',
    feed_empty_description: `Theo dõi những người dùng khác để xem bài viết của họ trong bảng tin của bạn. Càng nhiều người
            bạn theo dõi, bạn sẽ thấy nhiều nội dung hơn ở đây.`,
    find_people_follow: 'Tìm người để theo dõi',
    refetch_feed: 'Tải lại bảng tin',
    create_first_post: 'Tạo bài viết đầu tiên của bạn',
    adminPanel: 'Admin',
    dashboard: 'Bảng điều khiển',
    users: 'Người dùng',
    reportedPosts: 'Bài viết được báo cáo',
    reportSuccess: 'Báo cáo đã được gửi thành công!',
    reportFailed: 'Gửi báo cáo thất bại.',
    theme: 'Giao diện',
    themePreferences: 'Tùy chọn giao diện',
    selectTheme: 'Chọn giao diện',
    lightTheme: 'Giao diện sáng',
    darkTheme: 'Giao diện tối',
    systemTheme: 'Giao diện hệ thống',
    languageSettings: 'Cài đặt ngôn ngữ',
    selectLanguage: 'Chọn ngôn ngữ',
    vietnamese: 'Tiếng Việt',
    english: 'Tiếng Anh',
    japanese: 'Tiếng Nhật',
    preview: 'Xem trước',
    userManagement: 'Quản lý người dùng',
    manageUsersDescription: 'Quản lý người dùng và sửa đổi người dùng.',
    accessUserList: 'Truy cập danh sách người dùng',
    manageUsers: 'Quản lý người dùng',
    reviewReportedContent: 'Xem xét nội dung được báo cáo',
    viewReportedPostsDescription:
      'Xem xét và quản lý các bài viết đã bị báo cáo bởi người dùng.',
    manageReports: 'Quản lý báo cáo',
    preferences: 'Tùy chọn',
    action: 'Hành động',
    ban: 'Cấm',
    unban: 'Bỏ cấm',
    role: 'Vai trò',
    status: 'Trạng thái',
    admin: 'Quản trị',
    active: 'Hoạt động',
    statusFilter: 'Bộ lọc trạng thái',
    allStatuses: 'Tất cả trạng thái',
    pendingReview: 'Đang chờ xem xét',
    approved: 'Đã phê duyệt',
    reportCount: 'Số lượng báo cáo',
    allReports: 'Tất cả báo cáo',
    lowReport: 'Báo cáo thấp',
    mediumReport: 'Báo cáo trung bình',
    highReport: 'Báo cáo cao',
    author: 'Tác giả',
    contentPreview: 'Xem trước nội dung',
    visibility: 'Khả năng hiển thị',
    date: 'Ngày',
    view: 'Xem',
    approve: 'Phê duyệt',
    reports: 'báo cáo',
    hide: 'Ẩn',
    creating: 'Đang tạo',
    create_done: 'Tạo xong',
    banPost: 'Cấm bài viết',
    banPostConfirmation: 'Bạn có chắc chắn muốn cấm bài viết này không?',
    approvePost: 'Phê duyệt bài viết',
    approvePostConfirmation:
      'Bạn có chắc chắn muốn phê duyệt bài viết này không?',
    viewReportedPost: 'Xem bài viết đã báo cáo',
    close: 'Đóng',
    banUser: 'Cấm người dùng',
    unbanUser: 'Bỏ cấm người dùng',
    banUserConfirmation: 'Bạn có chắc chắn muốn cấm người dùng này không?',
    unbanUserConfirmation: 'Bạn có chắc chắn muốn bỏ cấm người dùng này không?',
    app: 'Ứng dụng',
  },
  ja: {
    user: 'ユーザー',
    home: 'ホーム',
    search: '検索',
    create: '作成',
    notifications: '通知',
    profile: 'プロフィール',
    settings: '設定',
    login: 'ログイン',
    register: '登録',
    forgotPassword: 'パスワードをお忘れですか',
    changePassword: 'パスワード変更',
    editProfile: 'プロフィール編集',
    darkMode: 'ダークモード',
    lightMode: 'ライトモード',
    language: '言語',
    logout: 'ログアウト',
    post: '投稿',
    comment: 'コメント',
    like: 'いいね',
    repost: 'リポスト',
    share: 'シェア',
    delete: '削除',
    edit: '編集',
    update: '更新',
    save: '保存',
    cancel: 'キャンセル',
    username: 'ユーザー名',
    email: 'メール',
    password: 'パスワード',
    confirmPassword: 'パスワード確認',
    bio: '自己紹介',
    displayName: '表示名',
    website: 'ウェブサイト',
    avatar: 'アバター',
    translate: '翻訳',
    viewEditHistory: '編集履歴を見る',
    reportContent: 'コンテンツを報告',
    followUser: 'フォロー',
    unfollowUser: 'フォロー解除',
    google: 'グーグル',
    error: 'エラー',
    banned: 'このプラットフォームから禁止されています。',
    emailNotVerified:
      'メールが確認されていません。 \n 登録したメールアドレスに確認メールを送信しました。受信トレイを確認し、すべての機能にアクセスするためにメールを確認してください。',
    emailVerified: 'メールが確認されました。',
    emptyFields: 'すべてのフィールドに入力してください。',
    loading: '読み込み中...',
    loginFailed: 'ログインに失敗しました。資格情報を確認してください。',
    success: '成功',
    googleLoginSuccess: 'Googleログインに成功しました!',
    googleLoginFailed: 'Googleログインに失敗したか、禁止されています。',
    verifySuccess: 'メール確認に成功しました!',
    verifySuccessDescription:
      'メールが正常に確認されました。アカウントは現在アクティブで、すべての機能を使用できます。',
    ifNotRedirect: '数秒後に自動的にホームページにリダイレクトされます。',
    resendEmailSuccess: '確認メールの再送信に成功しました!',
    resendEmailFailed: '確認メールの再送信に失敗しました。',
    name: '名前',
    registerFailed: 'アカウントまたはメールが存在するか、無効です。',
    followers: 'フォロワー',
    following: 'フォロー中',
    loading_image: '画像を読み込み中...',
    avatarUpdated: 'アバターが正常に更新されました!',
    avatarUpdateFailed: 'アバターの更新に失敗しました。',
    wallpaperUpdated: '壁紙が正常に更新されました!',
    wallpaperUpdateFailed: '壁紙の更新に失敗しました。',
    uploading: 'アップロード中...',
    uploadFailed: 'アップロードに失敗しました。',
    nameAndUsernameRequired: '名前とユーザー名は必須フィールドです。',
    profileUpdated: 'プロフィールが更新されました。',
    saving: '保存中...',
    settingUpdated: '設定が更新されました。',
    currentPassword: '現在のパスワード',
    newPassword: '新しいパスワード',
    passwordChanged: 'パスワードが正常に変更されました!',
    passwordChangeFailed: 'パスワードの変更に失敗しました。',
    passwordNotSuitable: 'パスワードが要件を満たしていません。',
    passwordsDoNotMatch: 'パスワードが一致しません。',
    passwordRequirements:
      'パスワードには、少なくとも1つの大文字、1つの小文字、1つの数字、および1つの特殊文字を含める必要があります。',
    passwordMustMatch: 'パスワードは確認用パスワードと一致する必要があります。',
    threadDetails: 'スレッドの詳細',
    public: '公開',
    followers_only: 'フォロワーのみ',
    only_me: '自分だけ',
    select_privacy: 'プライバシーを選択',
    post_empty: '投稿内容は空にできません。',
    post_created: '投稿が正常に作成されました!',
    post_create_failed: '投稿の作成に失敗しました。',
    post_updated: '投稿が正常に更新されました!',
    post_update_failed: '投稿の更新に失敗しました。',
    post_deleted: '投稿が正常に削除されました!',
    post_delete_failed: '投稿の削除に失敗しました。',
    no_comment_yet: 'まだコメントはありません。',
    comment_created: 'コメントが正常に作成されました!',
    comment_create_failed: 'コメントの作成に失敗しました。',
    noPosts: 'まだポストはありません。',
    noReposts: 'まだリポストはありません。',
    deletePost: '投稿を削除',
    confirmDeletePost: 'この投稿を削除してもよろしいですか?',
    threadDetail: 'スレッドの詳細',
    updating: '更新中...',
    posting: '投稿中...',
    noNotifications: 'まだ通知はありません。',
    notification_like: 'あなたの投稿にいいねしました',
    notification_likes: 'あなたの投稿に他の人がいいねしました',
    notification_comment: 'あなたの投稿にコメントしました',
    notification_repost: 'あなたの投稿をリポストしました',
    notification_reosts: 'あなたの投稿を他の人がリポストしました',
    notification_follow: 'あなたをフォローしました',
    notification: '通知',
    viewPost: '投稿を見る',
    markAllAsRead: 'すべて既読にする',
    loadingMoreNotifications: '通知をさらに読み込んでいます...',
    noMoreNotifications: 'これ以上の通知はありません。',
    follow: 'フォロー',
    unfollow: 'フォロー解除',
    noFollowers: 'フォロワーがいません',
    noFollowing: 'フォロー中の人はいません',
    removeFollower: 'フォロワーを削除',
    search_user: 'ユーザーを検索...',
    search_post: '投稿を検索...',
    no_user_found_for: 'に対してユーザーが見つかりませんでした',
    no_post_found_for: 'に対して投稿が見つかりませんでした',
    try_search_different_keywords:
      '別のキーワードで検索するか、スペルを確認してください。',
    searching_user: 'ユーザーを検索中...',
    searching_post: '投稿を検索中...',
    post_something: '何かを投稿...',
    feed: 'フィード',
    feed_loading: 'フィードを読み込んでいます...',
    feed_empty: 'フィードが空です。',
    feed_empty_description: `他のユーザーをフォローして、フィードに投稿を表示します。フォローする人が多いほど、
            ここで見るコンテンツが増えます。`,
    find_people_follow: '人を見つけてフォロー',
    refetch_feed: 'フィードを再取得',
    create_first_post: '最初の投稿を作成',
    adminPanel: '管理パネル',
    dashboard: 'ダッシュボード',
    users: 'ユーザー',
    reportedPosts: '報告された投稿',
    reportSuccess: '報告が正常に送信されました!',
    reportFailed: '報告の送信に失敗しました。',
    theme: 'テーマ',
    themePreferences: 'テーマの設定',
    selectTheme: 'テーマを選択',
    lightTheme: 'ライトテーマ',
    darkTheme: 'ダークテーマ',
    systemTheme: 'システムテーマ',
    languageSettings: '言語設定',
    selectLanguage: '言語を選択',
    vietnamese: 'ベトナム語',
    english: '英語',
    japanese: '日本語',
    preview: 'プレビュー',
    userManagement: 'ユーザー管理',
    manageUsersDescription: 'ユーザーを管理し、アカウントを監視します。',
    accessUserList: 'ユーザーリストにアクセス',
    manageUsers: 'ユーザーを管理',
    reviewReportedContent:
      '報告されたコンテンツを確認し、必要な措置を講じます。',
    viewReportedPostsDescription:
      '報告された投稿を確認し、適切な措置を講じます。',
    manageReports: '報告を管理',
    preferences: '設定',
    action: 'アクション',
    ban: '禁止',
    unban: '禁止解除',
    role: '役割',
    status: 'ステータス',
    admin: '管理者',
    active: 'アクティブ',
    statusFilter: 'ステータスフィルター',
    allStatuses: 'すべてのステータス',
    pendingReview: 'レビュー待ち',
    approved: '承認済み',
    reportCount: '報告数',
    allReports: 'すべての報告',
    lowReport: '低い報告',
    mediumReport: '中程度の報告',
    highReport: '高い報告',
    author: '著者',
    contentPreview: 'コンテンツプレビュー',
    visibility: '可視性',
    date: '日付',
    view: '表示',
    approve: '承認',
    reports: '報告',
    hide: '隠す',
    creating: '作成中',
    create_done: '作成完了',
    banPost: '投稿を禁止',
    banPostConfirmation: 'この投稿を禁止してもよろしいですか?',
    approvePost: '投稿を承認',
    approvePostConfirmation: 'この投稿を承認してもよろしいですか?',
    viewReportedPost: '報告された投稿を表示',
    close: '閉じる',
    banUser: 'ユーザーを禁止',
    unbanUser: 'ユーザーの禁止を解除',
    banUserConfirmation: 'このユーザーを禁止してもよろしいですか?',
    unbanUserConfirmation: 'このユーザーの禁止を解除してもよろしいですか?',
    app: 'アプリ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(Language.English);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'vi', 'ja'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return (
      translations[language][key as keyof (typeof translations)['en']] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
