import { Language } from "@/enums/Language";
import { Role } from "@/enums/Role";
import { Theme } from "@/enums/Theme";
import { Status, Visibility } from "@/enums/ThreadEnum";
import { IThread } from "@/interfaces/thread";
import { IUser } from "@/interfaces/user";

// Mock Users
export const mockUsers: IUser[] = [
  {
    email: "john.doe@example.com",
    username: "johndoe",
    name: "John Doe",
    avatar: "/placeholder.svg?height=40&width=40",
    wallpaper: "/placeholder.svg?height=200&width=600",
    bio: "Software developer and tech enthusiast",
    isEmailVerified: true,
    requiresUsernameChange: false,
    havePassword: true,
    role: Role.USER,
    status: "ACTIVE",
    isBanned: false,
    followers: [
      {
        name: "Jane Smith",
        username: "janesmith",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Alex Johnson",
        username: "alexj",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    following: [
      {
        name: "Emily Brown",
        username: "emilybrown",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    followersCount: 120,
    followingCount: 85,
    theme: Theme.Light,
    language: Language.English,
    createdAt: new Date("2023-01-15T10:30:00Z"),
    updatedAt: new Date("2023-05-20T14:45:00Z"),
  },
  {
    email: "jane.smith@example.com",
    username: "janesmith",
    name: "Jane Smith",
    avatar: "/placeholder.svg?height=40&width=40",
    wallpaper: "/placeholder.svg?height=200&width=600",
    bio: "Digital artist and designer",
    isEmailVerified: true,
    requiresUsernameChange: false,
    havePassword: true,
    role: Role.USER,
    status: "ACTIVE",
    isBanned: false,
    followers: [
      {
        name: "John Doe",
        username: "johndoe",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    following: [
      {
        name: "Sam Wilson",
        username: "samwilson",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Emily Brown",
        username: "emilybrown",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    followersCount: 350,
    followingCount: 210,
    theme: Theme.Dark,
    language: Language.English,
    createdAt: new Date("2023-02-10T08:15:00Z"),
    updatedAt: new Date("2023-06-05T11:20:00Z"),
  },
  {
    email: "alex.johnson@example.com",
    username: "alexj",
    name: "Alex Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    wallpaper: "/placeholder.svg?height=200&width=600",
    bio: "Travel blogger and photographer",
    isEmailVerified: true,
    requiresUsernameChange: false,
    havePassword: true,
    role: Role.USER,
    status: "INACTIVE",
    isBanned: true,
    followers: [],
    following: [
      {
        name: "John Doe",
        username: "johndoe",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    followersCount: 520,
    followingCount: 320,
    theme: Theme.System,
    language: Language.Vietnamese,
    createdAt: new Date("2023-03-05T12:45:00Z"),
    updatedAt: new Date("2023-07-12T09:30:00Z"),
  },
  {
    email: "sam.wilson@example.com",
    username: "samwilson",
    name: "Sam Wilson",
    avatar: "/placeholder.svg?height=40&width=40",
    wallpaper: "/placeholder.svg?height=200&width=600",
    bio: "Fitness coach and nutrition expert",
    isEmailVerified: true,
    requiresUsernameChange: false,
    havePassword: true,
    role: Role.USER,
    status: "ACTIVE",
    isBanned: false,
    followers: [
      {
        name: "Jane Smith",
        username: "janesmith",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    following: [],
    followersCount: 980,
    followingCount: 450,
    theme: Theme.Light,
    language: Language.English,
    createdAt: new Date("2023-04-20T15:10:00Z"),
    updatedAt: new Date("2023-08-18T16:25:00Z"),
  },
  {
    email: "emily.brown@example.com",
    username: "emilybrown",
    name: "Emily Brown",
    avatar: "/placeholder.svg?height=40&width=40",
    wallpaper: "/placeholder.svg?height=200&width=600",
    bio: "Food blogger and chef",
    isEmailVerified: true,
    requiresUsernameChange: false,
    havePassword: true,
    role: Role.ADMIN,
    status: "ACTIVE",
    isBanned: false,
    followers: [
      {
        name: "John Doe",
        username: "johndoe",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Jane Smith",
        username: "janesmith",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    following: [],
    followersCount: 750,
    followingCount: 380,
    theme: Theme.Dark,
    language: Language.Japanese,
    createdAt: new Date("2023-05-15T09:20:00Z"),
    updatedAt: new Date("2023-09-22T13:40:00Z"),
  },
];

// Mock Threads (Posts) with reportedNum field
export const mockThreads: IThread[] = [
  {
    _id: "101",
    user: {
      username: "johndoe",
      name: "John Doe",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    content:
      "Just launched my new website! Check it out and let me know what you think. #webdev #coding",
    status: Status.CREATE_DONE,
    visibility: Visibility.PUBLIC,
    reactionNum: 45,
    sharedNum: 12,
    commentNum: 8,
    reportedNum: 3,
    isLiked: false,
    isReThreaded: false,
    reactionBy: ["janesmith", "alexj", "emilybrown"],
    reThreadBy: [],
    media: [
      {
        url: "/placeholder.svg?height=300&width=400",
        type: "image",
      },
    ],
    createdAt: new Date("2023-10-05T14:30:00Z"),
    updatedAt: new Date("2023-10-05T14:30:00Z"),
  },
  {
    _id: "102",
    user: {
      username: "janesmith",
      name: "Jane Smith",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    content:
      "My latest digital art piece. Inspired by cyberpunk aesthetics and futuristic cityscapes. #digitalart #cyberpunk",
    status: Status.CREATE_DONE,
    visibility: Visibility.PUBLIC,
    reactionNum: 120,
    sharedNum: 35,
    commentNum: 22,
    reportedNum: 5,
    isLiked: true,
    isReThreaded: false,
    reactionBy: ["johndoe", "alexj", "samwilson", "emilybrown"],
    reThreadBy: ["johndoe", "alexj", "samwilson"],
    media: [
      {
        url: "/placeholder.svg?height=300&width=400",
        type: "image",
      },
      {
        url: "/placeholder.svg?height=300&width=400",
        type: "image",
      },
    ],
    createdAt: new Date("2023-10-08T10:15:00Z"),
    updatedAt: new Date("2023-10-08T10:15:00Z"),
  },
  {
    _id: "103",
    user: {
      username: "alexj",
      name: "Alex Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    content:
      "Exploring the beautiful beaches of Bali this week! The sunset views are absolutely breathtaking. #travel #bali",
    status: Status.PENDING,
    visibility: Visibility.PUBLIC,
    reactionNum: 210,
    sharedNum: 48,
    commentNum: 32,
    reportedNum: 2,
    isLiked: false,
    isReThreaded: true,
    reactionBy: ["johndoe", "janesmith", "samwilson", "emilybrown"],
    reThreadBy: ["johndoe", "janesmith"],
    media: [
      {
        url: "/placeholder.svg?height=300&width=400",
        type: "image",
      },
    ],
    createdAt: new Date("2023-10-12T16:45:00Z"),
    updatedAt: new Date("2023-10-12T16:45:00Z"),
  },
  {
    _id: "104",
    user: {
      username: "samwilson",
      name: "Sam Wilson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    content:
      "New workout routine just dropped! 30 minutes of high-intensity interval training that you can do at home with no equipment. #fitness #workout",
    status: Status.CREATE_DONE,
    visibility: Visibility.FOLLOWER_ONLY,
    reactionNum: 85,
    sharedNum: 28,
    commentNum: 15,
    reportedNum: 0,
    isLiked: true,
    isReThreaded: false,
    reactionBy: ["johndoe", "janesmith", "emilybrown"],
    reThreadBy: ["janesmith", "emilybrown"],
    media: [],
    createdAt: new Date("2023-10-15T08:20:00Z"),
    updatedAt: new Date("2023-10-15T08:20:00Z"),
  },
  {
    _id: "105",
    user: {
      username: "emilybrown",
      name: "Emily Brown",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    content:
      "Made this delicious homemade pasta with fresh tomato sauce and basil from my garden. Recipe in the comments! #food #cooking",
    status: Status.HIDE,
    visibility: Visibility.PUBLIC,
    reactionNum: 150,
    sharedNum: 42,
    commentNum: 28,
    reportedNum: 8,
    isLiked: false,
    isReThreaded: false,
    reactionBy: ["johndoe", "janesmith", "alexj", "samwilson"],
    reThreadBy: ["johndoe", "janesmith", "alexj"],
    media: [
      {
        url: "/placeholder.svg?height=300&width=400",
        type: "image",
      },
    ],
    createdAt: new Date("2023-10-18T12:10:00Z"),
    updatedAt: new Date("2023-10-18T12:10:00Z"),
  },
  {
    _id: "106",
    user: {
      username: "janesmith",
      name: "Jane Smith",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    content:
      "This is potentially harmful content that has been reported multiple times. #controversial",
    status: Status.PENDING,
    visibility: Visibility.PUBLIC,
    reactionNum: 75,
    sharedNum: 30,
    commentNum: 45,
    reportedNum: 12,
    isLiked: false,
    isReThreaded: false,
    reactionBy: ["alexj", "samwilson", "emilybrown"],
    reThreadBy: ["alexj", "samwilson"],
    media: [],
    createdAt: new Date("2023-10-20T09:30:00Z"),
    updatedAt: new Date("2023-10-20T09:30:00Z"),
  },
  {
    _id: "107",
    user: {
      username: "alexj",
      name: "Alex Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    content:
      "Another post with multiple reports due to questionable content. #disputed",
    status: Status.PENDING,
    visibility: Visibility.PRIVATE,
    reactionNum: 60,
    sharedNum: 25,
    commentNum: 38,
    reportedNum: 7,
    isLiked: false,
    isReThreaded: false,
    reactionBy: ["johndoe", "janesmith", "emilybrown"],
    reThreadBy: ["johndoe", "emilybrown"],
    media: [],
    createdAt: new Date("2023-10-21T14:15:00Z"),
    updatedAt: new Date("2023-10-21T14:15:00Z"),
  },
];
